version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tweet-sentiment-analyzer-backend-1
    ports:
      - "8000:8000"
    networks:
      - sentiment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: tweet-sentiment-analyzer-frontend-1
    ports:
      - "8501:8501" # Streamlit's default port
    networks:
      - sentiment-network
    environment:
      # This is the crucial line that tells the Streamlit container
      # how to find the backend container on Docker's internal network.
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      # This is the reliable way to check if Streamlit is running.
      # We check the main page instead of the unreliable _stcore endpoint.
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  sentiment-network:
    driver: bridge